site_name: Cookiecutter Pypackage Instance
site_description: "🐍 An awesome python package by the name Cookiecutter Pypackage Instance"
site_url: "https://billsioros.github.io/cookiecutter-pypackage-instance/"
repo_url: "https://github.com/billsioros/cookiecutter-pypackage-instance"
edit_uri: "edit/master/docs/"
repo_name: "billsioros/cookiecutter-pypackage-instance"
copyright: |
  Copyright &copy; 2023-2023 <a href="https://github.com/billsioros" target="_blank" rel="noopener">Vasilis Sioros</a>
nav:
  - Overview: index.md
  - Code Reference:
      - Cookiecutter Pypackage Instance: src/cookiecutter_pypackage_instance.md
  - Contributing:
      - Contributing Guidelines: CONTRIBUTING.md
      - Code Of Conduct: CODE_OF_CONDUCT.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
theme:
  name: material
  features:
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          rendering:
            show_source: true
          options:
            docstring_style: google
            docstring_options:
            ignore_init_summary: yes
            merge_init_into_class: yes
            show_submodules: no
  - minify:
      minify_html: true
markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: ¤
  - mdx_truly_sane_lists
watch:
  - src/cookiecutter-pypackage-instance
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/billsioros
  version:
    provider: mike
