name: Code Coverage

on:
  push:
    paths:
    - 'cookiecutter_pypackage_instance/**/*.py'
    - 'tests/**/*.py'
    - 'pyproject.toml'

jobs:
  codecov:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: 3.8

        - name: Install Poetry
          uses: abatilo/actions-poetry@v2.1.4
          with:
            poetry-version: 1.1.8

        - name: Configure Poetry
          run: |
            poetry config virtualenvs.in-project true

        - name: Set up cache
          uses: actions/cache@v3.0.4
          with:
            path: .venv
            key: venv-${{ hashFiles('**/poetry.lock') }}

        - name: Install dependencies
          run: |
            poetry install

        - name: Generate the coverage report
          run: |
            poetry run python -m pytest -p no:sugar --cov=./src/cookiecutter_pypackage_instance --cov-report=xml

        - name: Upload coverage report
          uses: codecov/codecov-action@v3
